spring:
  application:
    name: news-alpha-backend
  config:
    import: optional:classpath:application-secret.yml
  datasource:
    url: jdbc:postgresql://${POSTGRE_DB_HOST:localhost}:5432/news_db
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

naver:
  news:
    supported-domains:
      - https://n.news.naver.com/
      - https://sports.news.naver.com/
      - https://entertain.naver.com/

custom:
  access-log:
    static-patterns:
      - "/css/**"
      - "/js/**"
      - "/images/**"
      - "/favicon.ico"
      - "/error"
